Fix var ctrl is undefined.
I got an error in line 449 due to that ctrl is undefined.
Thanks.

```
TypeError: Cannot set property '$render' of undefined
    at link (http://localhost:1337/js/dependencies/dynamic-forms.js:449:24)
```